[package]
name = "day-10"
version = "0.1.0"
authors = ["Matt Diamant <matt.diamant@dictionary.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day-10"
path = "day-10.rs"
